# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-20201119
    #container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  firefox:
    image: selenium/node-firefox:3.141.59-20201119
    #container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.141.59-20201119
    ports:
      - "4444:4444"